In [32]:
# Part 1 and 2

inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
print(output)


[4.8, 1.21, 2.385]


In [33]:
print(sys.executable)

c:\Users\JDSan\.virtualenvs\neuralNetworkPractice-LP908O5V\Scripts\python.exe


In [34]:
import numpy as np

In [35]:
# Part 3

inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.5, -0.91, 0.26, -0.5], 
            [-0.26, -0.27, 0.17, 0.87] ]
biases = [2, 3, 0.5]

output = np.dot(weights, inputs) + biases

print(output)

# Does the same as above but with more code
weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.5, -0.91, 0.26, -0.5], 
            [-0.26, -0.27, 0.17, 0.87] ]

biases = [2, 3, 0.5]

layer_outputs = [] # Output of current layer
for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0 # Output of given neuron
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs)


AttributeError: 'list' object has no attribute 'astype'

In [ ]:
# Part 4

# inputs = [[1.0, 2.0, 3.0, 2.5],
#           [2.0, 5.0, -1.0, 2.0],
#           [-1.5, 2.7, 3.3, -0.8]]

# weights = [[0.2, 0.8, -0.5, 1.0], 
#            [0.5, -0.91, 0.26, -0.5], 
#             [-0.26, -0.27, 0.17, 0.87]]

# biases = [2, 3, 0.5]

# weights2 = [[0.1, -0.14, 0.5], 
#            [-0.5, 0.12, -0.33], 
#             [-0.44, 0.73, -0.13]]

# biases2 = [-1, 2 , -0.5]

# layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
# layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

# print(layer2_outputs)

np.random.seed(0)
X = [[1.0, 2.0, 3.0, 2.5], 
     [2.0, 5.0, -1.0, 2.0], 
     [-1.5, 2.7, 3.3, -0.8]]


class Layer_Dense:
    
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) # Note: Generates a lol on numbers between -1 and 1.
        self.biases = np.zeros((1, n_neurons)) # Note: Best to start with biases as 0 unless there is a likely hood of the zero propegating through the network, resulting in a "dead" network.
    def forward(self, inputs):
        self.output =  np.dot(inputs, self.weights) + self.biases
    
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
# print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)


In [ ]:
# Part 5
np.random.seed(0)

# https://cs231n.github.io/neural-networks-case-study/


def create_data(points, classes):
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r=np.linspace(0.0, 1, points) # radius
        t=np.linspace(class_number*4, (class_number+1)*4, points)+np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix]=class_number
    return X,y
import matplotlib.pyplot as plt

print("here")
X,y=create_data(100,3)
plt.scatter(X[:,0],X[:,1])
plt.show()
plt.scatter(X[:,0],X[:,1],c=y,cmap="brg")
plt.show()

In [ ]:
import nnfs
from nnfs.datasets import spiral_data

In [ ]:
# Part 5 - Activation functions

'''Types of activation functions
- Step function: result will either be a 1 or 0  https://youtu.be/gmjzbpSVY1A?t=58
- Sigmoid function: alot more granular output. Helps figure out accuracy of neural network more accurately  https://youtu.be/gmjzbpSVY1A?t=203
- Rectified linear unit activation function: granular, similar to sigmoid, but faster because its a simpler calculation  https://youtu.be/gmjzbpSVY1A?t=267
'''


'''inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []


# Rectified linear unit activation function
# for i in inputs:
#     if i>0:
#         output.append(i)
#     elif i <= 0:
#         output.append(0)
# print(output)
# another way of doing the rlua is the following:
for i in inputs:
    output.append(max(0,i))
# print(output)'''


nnfs.init()


X, y = spiral_data(100,3)



class Layer_Dense:
    
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) 
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output =  np.dot(inputs, self.weights) + self.biases
        
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
    
    
layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer1.forward(X)
print(layer1.output)
activation1.forward(X)
print(activation1.output)

In [ ]:
# Part 6 - Softmax Activation
# Expotential function
# Euler's number

nnfs.init()

layer_outputs =[[4.8, 1.21, 2.385],
                [8.9, -1.81, 0.2],
                [1.41, 1.051, 0.026]]

# Exponentiate
exp_values = np.exp(layer_outputs)

print('exponentiated values: ',exp_values)

# Normalisation
norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True)
    
print('normalised values: ',norm_values)
# print('normalised values sum: ', sum(norm_values))

In [37]:
# Part 6


nnfs.init()


class Layer_Dense:
    
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) 
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output =  np.dot(inputs, self.weights) + self.biases
        
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities
        
X,y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()
dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
